### PR TITLE
Get wallet information through bg script

### PR DESCRIPTION
**Pull request by scriptfans**

### CODE REVIEW

**Comment by dwalintukan** [comment]
do we need to have so many function calls just for an RPC call? this is all the functions that it needs to for an RPC call:

```
contentscript.window.listener
-> contentscript.handleContentScriptMessage() 
-> contentscript.handleRPCCallMessage()
-> contentscript.responseExtensionAPI()
-> window.postMessage(target: inpage) 
-> inpage.window.listener
-> inpage.handleInpageMessage()
-> utils.handleRpcCallResponse()
```

My question is, why do we need to go from `contentscript` to `inpage`? This seems backwards according to Metamask's architecture: https://github.com/MetaMask/metamask-extension

**Comment by scriptfans** [comment]
@dwalintukan We need communication from content script to inpage, because we need to return the result of the API call to the page.

Btw, I found that performing asynchronous operations directly in the handler and returning data is impossible:

`
const result = await this.callRpc(request.id, request.method, request.args);
sendResponse(result);  
`
At listener side, the result will be undefined, So I can only send a message to content script again, Then forward it to the page (DApp) .

**Comment by scriptfans** [comment]
Dapp's website can use it like this:
`
const result = await window.qryptoRpcProvider.rawCall('callContract', ['b10071ee33512ce8a0c06ecbc14a5f585a27a3e2', 'e179b912']));
console.log(result);
`

**Comment by dwalintukan** [comment]
@scriptfans gotcha. so we have to do `contentscript` -> `background` -> `contentscript` -> `inpage` to get it back to the user then? 🐑

**Pull request merged**
